table 'Product ACV Measures'
	lineageTag: 8a8b8d88-1ed3-424f-be02-b444c7cc7e10

	measure 'Product ACV CW' = CALCULATE(SUM(VW_F_PRODUCT_ACV[PRODUCT_ACV]),VW_F_PRODUCT_ACV[CLOSED_ACV_COUNT] = 1)
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 6f318974-f812-411b-82d4-79013bb51de1

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Product ASP' = CALCULATE(DIVIDE('Product ACV Measures'[Product ACV CW],DISTINCTCOUNT(VW_F_PRODUCT_ACV[OPPORTUNITY_ID]),0),VW_F_PRODUCT_ACV[ASP_COUNT_PRODUCT] = 1)
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 01f59b24-bc80-42fc-9e37-88a219defa1d

	measure 'Product Deal Volume' = CALCULATE(DISTINCTCOUNT(VW_F_PRODUCT_ACV[OPPORTUNITY_ID]),VW_F_PRODUCT_ACV[STAGE_NAME] = "Closed Won",VW_F_PRODUCT_ACV[PRODUCT_ACV] <> 0 && VW_F_PRODUCT_ACV[CLOSED_ACV_COUNT] = 1 )
		formatString: #,0
		lineageTag: 300bc5d6-02c2-4a05-a722-3f95bec5f53c

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Product Lost Volume' = CALCULATE(DISTINCTCOUNT(VW_F_PRODUCT_ACV[OPPORTUNITY_ID]),VW_F_PRODUCT_ACV[STAGE_NAME] = "Closed Lost",VW_F_PRODUCT_ACV[RENEWAL_OPPTY_TYPE_FLAG] = FALSE())
		formatString: #,0
		lineageTag: 94319785-f826-4b3f-ac9c-58d9497c1b2d

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Product Closed Lost ACV' = CALCULATE(SUM(VW_F_PRODUCT_ACV[PRODUCT_ACV]),VW_F_PRODUCT_ACV[STAGE_NAME] = "Closed Lost")
		lineageTag: d379be24-3779-4469-9548-c1422bf6cc19

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Product Win Rate' = CALCULATE(DIVIDE([Product ACV CW],[Product ACV CW]+[Product Closed Lost ACV],0),VW_F_PRODUCT_ACV[RENEWAL_OPPTY_TYPE_FLAG] = FALSE())
		formatString: 0%;-0%;0%
		lineageTag: 257e663e-c2ae-4ac6-8ff8-2635c4ff9a4e

	measure 'P_Land ACV' = CALCULATE('Product ACV Measures'[Product ACV CW],VW_F_PRODUCT_ACV[LAND_ACV_COUNT] =1)
		lineageTag: 42a189d3-2613-4f08-a78d-ec841cb61539

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'P_LAND % OF ACV' = DIVIDE([P_Land ACV],[Product ACV CW],0)
		formatString: #,0%;-#,0%;#,0%
		lineageTag: 011cee96-ac91-4224-9656-228dbd402149

	measure 'P_EXPAND ACV' = CALCULATE('Product ACV Measures'[Product ACV CW],VW_F_PRODUCT_ACV[LAND_ACV_COUNT] <> 1)
		lineageTag: 001a40af-26db-4483-b3d0-2d16ebc8a4ca

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'P_EXPAND % OF ACV' = DIVIDE([P_EXPAND ACV],'Product ACV Measures'[Product ACV CW],0)
		formatString: #,0%;-#,0%;#,0%
		lineageTag: b5f73878-dee6-4f57-b9c2-57b5c3b24f13

	measure 'P_MY % of ACV' = DIVIDE([Multi-Year ACV],'Product ACV Measures'[Product ACV CW],0)
		formatString: 0%;-0%;0%
		lineageTag: 27132015-d966-4ac6-8230-02da36b882bb

	measure 'P_Sales Cycle' = CALCULATE(AVERAGE(VW_F_PRODUCT_ACV[SALES_CYCLE]),VW_F_PRODUCT_ACV[PRODUCT_ACV] <> 0 && VW_F_PRODUCT_ACV[CLOSED_ACV_COUNT] = 1 )
		formatString: 0
		lineageTag: e4f8dfe0-23f1-425b-bfa6-2796fbb4f846

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Multi-Year ACV' = CALCULATE('Product ACV Measures'[Product ACV CW],VW_F_PRODUCT_ACV[MY_WON_ACV] <> 0)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: a35bb47c-8783-4215-8d65-404a373304c9

	measure 'Professional Services Fees' = CALCULATE(SUM(VW_F_PRODUCT_ACV[SERVICES_FEES]),VW_F_PRODUCT_ACV[PRODUCT_FAMILY] = "Professional Services", VW_F_PRODUCT_ACV[CLOSED_ACV_COUNT] = 1)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 5f00ab32-c56d-40f8-9094-21faca8c7b8f

	measure 'Services ACV' = CALCULATE(SUM(VW_F_PRODUCT_ACV[PRODUCT_ACV]),GROUPBY(VW_F_PRODUCT_ACV,VW_F_ACV[OPPORTUNITY_ID]),VW_F_PRODUCT_ACV[SERVICES_FEES] <> BLANK())
		formatString: 0
		lineageTag: cad9c593-342e-491b-b9dc-430f0dbbd5a8

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'ACV_Service %' = DIVIDE([Services_Fees],[Product ACV CW],0)
		formatString: 0%;-0%;0%
		lineageTag: 2e4cc813-d1e0-4a21-be13-596571a69047

	measure Services_Fees = CALCULATE(SUM(VW_F_PRODUCT_ACV[SERVICES_FEES]),VW_F_PRODUCT_ACV[CLOSED_ACV_COUNT] = 1)
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: a15799d9-98b2-4600-8512-94d570b72a0e

	partition 'Product ACV Measures' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

